"""
NARX Weight Exporter — generates ESP32-ready C inference code.

After training narx_model.py, run this script to produce:
  - narx_weights.h       : weight/bias arrays + normalization defines
  - narx_inference.h     : public API declarations
  - narx_inference.c     : pure C inference (no external dependencies)

The generated files can be copied directly into the PlatformIO source tree:
  esp32-firmware/sensing/src/

Usage:
    python -m soc_estimation.narx.narx_export
"""

import sys
import json
import logging
import numpy as np
import tensorflow as tf
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from soc_estimation.data.preprocess import load_scaler_params, SCALER_PATH

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

NARX_DIR = Path(__file__).resolve().parent
NARX_N = 5
NARX_M = 3


def fmt_float(v: float) -> str:
    """Format a float as a C float literal."""
    return f"{v:.8f}f"


def fmt_array_1d(arr: np.ndarray) -> str:
    """Format a 1-D numpy array as a C initializer list."""
    return "{ " + ", ".join(fmt_float(x) for x in arr.flat) + " }"


def fmt_array_2d(arr: np.ndarray) -> str:
    """Format a 2-D numpy array as a nested C initializer list (row-major)."""
    rows = []
    for row in arr:
        rows.append("    { " + ", ".join(fmt_float(x) for x in row) + " }")
    return "{\n" + ",\n".join(rows) + "\n}"


def generate_weights_header(model: tf.keras.Model, scaler_params: dict, out_path: Path):
    """Write narx_weights.h with all weights, biases, and scaler defines."""
    layers = [l for l in model.layers if len(l.get_weights()) > 0]
    assert len(layers) == 3, f"Expected 3 trainable layers, got {len(layers)}"

    W1, b1 = layers[0].get_weights()   # (18, 16), (16,)
    W2, b2 = layers[1].get_weights()   # (16,  8), ( 8,)
    W3, b3 = layers[2].get_weights()   # ( 8,  1), ( 1,)

    sp = scaler_params
    lines = [
        "/**",
        " * narx_weights.h",
        " * Auto-generated by narx_export.py — DO NOT EDIT.",
        " *",
        " * NARX SOC model weights for ESP32 inference.",
        " * Architecture: 18 -> 16 (ReLU) -> 8 (ReLU) -> 1 (linear)",
        f" * Total parameters: {model.count_params()}",
        " */",
        "#pragma once",
        "",
        "/* ---- Network dimensions ---- */",
        f"#define NARX_INPUT_SIZE    {W1.shape[0]}",
        f"#define NARX_HIDDEN1_SIZE  {W1.shape[1]}",
        f"#define NARX_HIDDEN2_SIZE  {W2.shape[1]}",
        f"#define NARX_OUTPUT_SIZE   {W3.shape[1]}",
        f"#define NARX_WINDOW_N      {NARX_N}",
        f"#define NARX_FEEDBACK_M    {NARX_M}",
        "",
        "/* ---- Normalization parameters (fit on training data) ---- */",
        f"#define NORM_V_MIN    {fmt_float(sp['voltage']['min'])}",
        f"#define NORM_V_MAX    {fmt_float(sp['voltage']['max'])}",
        f"#define NORM_I_MIN    {fmt_float(sp['current']['min'])}",
        f"#define NORM_I_MAX    {fmt_float(sp['current']['max'])}",
        f"#define NORM_T_MIN    {fmt_float(sp['temperature']['min'])}",
        f"#define NORM_T_MAX    {fmt_float(sp['temperature']['max'])}",
        f"#define NORM_SOC_MIN  {fmt_float(sp['soc']['min'])}",
        f"#define NORM_SOC_MAX  {fmt_float(sp['soc']['max'])}",
        "",
        "/* ---- Layer 1 weights: W1[INPUT][HIDDEN1] ---- */",
        f"static const float W1[NARX_INPUT_SIZE][NARX_HIDDEN1_SIZE] = {fmt_array_2d(W1)};",
        "",
        f"static const float b1[NARX_HIDDEN1_SIZE] = {fmt_array_1d(b1)};",
        "",
        "/* ---- Layer 2 weights: W2[HIDDEN1][HIDDEN2] ---- */",
        f"static const float W2[NARX_HIDDEN1_SIZE][NARX_HIDDEN2_SIZE] = {fmt_array_2d(W2)};",
        "",
        f"static const float b2[NARX_HIDDEN2_SIZE] = {fmt_array_1d(b2)};",
        "",
        "/* ---- Layer 3 weights: W3[HIDDEN2][OUTPUT] ---- */",
        f"static const float W3[NARX_HIDDEN2_SIZE][NARX_OUTPUT_SIZE] = {fmt_array_2d(W3)};",
        "",
        f"static const float b3[NARX_OUTPUT_SIZE] = {fmt_array_1d(b3)};",
        "",
    ]

    out_path.write_text("\n".join(lines))
    logger.info(f"Written: {out_path}")


def generate_header(out_path: Path):
    """Write narx_inference.h — public API."""
    content = """\
/**
 * narx_inference.h
 * Auto-generated by narx_export.py — DO NOT EDIT.
 *
 * Public API for NARX SOC estimation on ESP32.
 *
 * Usage:
 *   #include "narx_inference.h"
 *
 *   // Call once in setup()
 *   narx_init();
 *
 *   // When the RPi sends a corrected SOC from the cloud LSTM, reset the buffer:
 *   narx_reset(cloud_soc_percent);
 *
 *   // Call every second in loop()
 *   float soc_percent = narx_predict(voltage_V, current_A, temperature_C);
 *
 * Input:
 *   voltage_V     — pack voltage in Volts (raw, unnormalized)
 *   current_A     — pack current in Amperes (negative = discharge). Pass 0.0f
 *                   if current is unavailable on the sensing ESP32.
 *   temperature_C — module temperature in °C (raw, unnormalized)
 *
 * Output:
 *   SOC in percent [0.0, 100.0]
 *
 * Architecture notes:
 *   The NARX model uses teacher-forced training and is most accurate immediately
 *   after narx_reset() is called with a cloud LSTM correction. The cloud LSTM
 *   (running on the RPi/Docker) is the authoritative SOC source; the NARX
 *   provides fast local tracking between cloud updates.
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Reset internal sliding-window and SOC feedback buffers.
 * Must be called once before the first narx_predict() call.
 */
void narx_init(void);

/**
 * Reset the SOC feedback buffer to a known value.
 * Call this whenever the cloud LSTM provides a corrected SOC estimate.
 *
 * soc_percent — known SOC in percent [0.0, 100.0]
 */
void narx_reset(float soc_percent);

/**
 * Run one step of NARX SOC estimation.
 * Returns predicted SOC in percent [0.0, 100.0].
 */
float narx_predict(float voltage_V, float current_A, float temperature_C);

#ifdef __cplusplus
}
#endif
"""
    out_path.write_text(content)
    logger.info(f"Written: {out_path}")


def generate_inference_c(out_path: Path):
    """Write narx_inference.c — pure C implementation."""
    content = """\
/**
 * narx_inference.c
 * Auto-generated by narx_export.py — DO NOT EDIT.
 *
 * Pure C NARX SOC inference for ESP32 / Arduino / ESP-IDF.
 * Dependencies: <math.h> only.
 *
 * Compile check (host):
 *   gcc -Wall -Wextra -std=c99 -lm narx_inference.c -o /dev/null
 */

#include "narx_inference.h"
#include "narx_weights.h"
#include <math.h>

/* ------------------------------------------------------------------ */
/*  Internal state                                                       */
/* ------------------------------------------------------------------ */

/* Circular buffers for sensor sliding window */
static float _v_buf[NARX_WINDOW_N];
static float _i_buf[NARX_WINDOW_N];
static float _t_buf[NARX_WINDOW_N];

/* SOC feedback buffer (stores last M normalized predictions) */
static float _soc_buf[NARX_FEEDBACK_M];

/* Write index into the circular buffers */
static int _buf_idx;

/* ------------------------------------------------------------------ */
/*  Helpers                                                              */
/* ------------------------------------------------------------------ */

static float _normalize(float val, float mn, float mx)
{
    float range = mx - mn;
    if (range < 1e-8f) range = 1e-8f;
    return (val - mn) / range;
}

static float _relu(float x)
{
    return x > 0.0f ? x : 0.0f;
}

static float _clampf(float x, float lo, float hi)
{
    if (x < lo) return lo;
    if (x > hi) return hi;
    return x;
}

/* ------------------------------------------------------------------ */
/*  Public API                                                           */
/* ------------------------------------------------------------------ */

void narx_init(void)
{
    int i;
    for (i = 0; i < NARX_WINDOW_N; i++) {
        _v_buf[i] = 0.0f;
        _i_buf[i] = 0.0f;
        _t_buf[i] = 0.0f;
    }
    /* Initialize SOC feedback at 0.5 (= 50% normalized) */
    for (i = 0; i < NARX_FEEDBACK_M; i++) {
        _soc_buf[i] = 0.5f;
    }
    _buf_idx = 0;
}

void narx_reset(float soc_percent)
{
    int i;
    float soc_norm;
    float range = NORM_SOC_MAX - NORM_SOC_MIN;
    if (range < 1e-8f) range = 1e-8f;
    soc_norm = _clampf((soc_percent - NORM_SOC_MIN) / range, 0.0f, 1.0f);
    for (i = 0; i < NARX_FEEDBACK_M; i++) {
        _soc_buf[i] = soc_norm;
    }
}

float narx_predict(float voltage_V, float current_A, float temperature_C)
{
    int i, j;
    int oldest;
    float input[NARX_INPUT_SIZE];
    float h1[NARX_HIDDEN1_SIZE];
    float h2[NARX_HIDDEN2_SIZE];
    float out;
    float soc_norm;

    /* ---- 1. Normalize inputs ---- */
    float v_n = _normalize(voltage_V,     NORM_V_MIN, NORM_V_MAX);
    float i_n = _normalize(current_A,     NORM_I_MIN, NORM_I_MAX);
    float t_n = _normalize(temperature_C, NORM_T_MIN, NORM_T_MAX);

    /* ---- 2. Write into circular buffers ---- */
    int slot = _buf_idx % NARX_WINDOW_N;
    _v_buf[slot] = v_n;
    _i_buf[slot] = i_n;
    _t_buf[slot] = t_n;
    _buf_idx++;

    /* ---- 3. Build flat input vector [v_win | i_win | t_win | soc_fb] ---- */
    /* oldest sample sits at (_buf_idx) % NARX_WINDOW_N */
    oldest = _buf_idx % NARX_WINDOW_N;
    for (j = 0; j < NARX_WINDOW_N; j++) {
        int idx = (oldest + j) % NARX_WINDOW_N;
        input[j]                      = _v_buf[idx];
        input[j + NARX_WINDOW_N]      = _i_buf[idx];
        input[j + 2 * NARX_WINDOW_N]  = _t_buf[idx];
    }
    for (j = 0; j < NARX_FEEDBACK_M; j++) {
        input[3 * NARX_WINDOW_N + j] = _soc_buf[j];
    }

    /* ---- 4. Forward pass: Dense1 (ReLU) ---- */
    for (i = 0; i < NARX_HIDDEN1_SIZE; i++) {
        h1[i] = b1[i];
        for (j = 0; j < NARX_INPUT_SIZE; j++) {
            h1[i] += input[j] * W1[j][i];
        }
        h1[i] = _relu(h1[i]);
    }

    /* ---- 5. Forward pass: Dense2 (ReLU) ---- */
    for (i = 0; i < NARX_HIDDEN2_SIZE; i++) {
        h2[i] = b2[i];
        for (j = 0; j < NARX_HIDDEN1_SIZE; j++) {
            h2[i] += h1[j] * W2[j][i];
        }
        h2[i] = _relu(h2[i]);
    }

    /* ---- 6. Forward pass: Dense3 (linear output) ---- */
    out = b3[0];
    for (j = 0; j < NARX_HIDDEN2_SIZE; j++) {
        out += h2[j] * W3[j][0];
    }

    /* ---- 7. Clamp to [0, 1] normalized range ---- */
    soc_norm = _clampf(out, 0.0f, 1.0f);

    /* ---- 8. Shift SOC feedback buffer and append new prediction ---- */
    for (j = 0; j < NARX_FEEDBACK_M - 1; j++) {
        _soc_buf[j] = _soc_buf[j + 1];
    }
    _soc_buf[NARX_FEEDBACK_M - 1] = soc_norm;

    /* ---- 9. Denormalize and return SOC percentage ---- */
    return soc_norm * (NORM_SOC_MAX - NORM_SOC_MIN) + NORM_SOC_MIN;
}
"""
    out_path.write_text(content)
    logger.info(f"Written: {out_path}")


def verify_c_vs_keras(model: tf.keras.Model, scaler_params: dict, n_samples: int = 10):
    """
    Numerically verify that the C weight arrays match Keras predictions
    by running identical inputs through both and comparing outputs.
    Uses Python to simulate the C forward pass exactly.
    """
    logger.info("Verifying C weights match Keras model...")

    sp = scaler_params
    layers = [l for l in model.layers if len(l.get_weights()) > 0]
    W1, b1 = layers[0].get_weights()
    W2, b2 = layers[1].get_weights()
    W3, b3 = layers[2].get_weights()

    def c_forward(x_norm):
        """Simulate the C forward pass in Python."""
        h1 = np.maximum(0, x_norm @ W1 + b1)
        h2 = np.maximum(0, h1 @ W2 + b2)
        out = h2 @ W3 + b3
        return np.clip(out, 0.0, 1.0)

    rng = np.random.default_rng(42)
    max_diff = 0.0

    for _ in range(n_samples):
        # Random normalized input
        x = rng.uniform(0, 1, size=(1, 18)).astype(np.float32)

        keras_out = model.predict(x, verbose=0).flatten()[0]
        c_out = c_forward(x).flatten()[0]

        diff = abs(float(keras_out) - float(c_out))
        max_diff = max(max_diff, diff)

    logger.info(f"Max Keras vs C difference across {n_samples} samples: {max_diff:.2e}")
    if max_diff < 1e-5:
        logger.info("PASS: C weights match Keras output.")
    else:
        logger.warning(f"WARN: Difference {max_diff:.2e} exceeds 1e-5 threshold.")


def main():
    model_path = NARX_DIR / "narx_soc_model.keras"
    if not model_path.exists():
        logger.error(f"Trained model not found at {model_path}")
        logger.error("Run narx_model.py first to train the model.")
        sys.exit(1)

    logger.info(f"Loading model from {model_path}")
    model = tf.keras.models.load_model(model_path)
    model.summary()

    scaler_params = load_scaler_params(SCALER_PATH)
    logger.info(f"Scaler params loaded from {SCALER_PATH}")

    # Generate C files
    generate_weights_header(model, scaler_params, NARX_DIR / "narx_weights.h")
    generate_header(NARX_DIR / "narx_inference.h")
    generate_inference_c(NARX_DIR / "narx_inference.c")

    # Numerical verification
    verify_c_vs_keras(model, scaler_params)

    # Memory estimate
    param_count = model.count_params()
    flash_bytes = param_count * 4
    ram_bytes = (NARX_N * 3 + NARX_M + 16 + 8) * 4
    logger.info(f"Memory footprint: ~{flash_bytes} bytes flash (weights), ~{ram_bytes} bytes RAM (buffers)")
    logger.info("Export complete. Copy narx_weights.h, narx_inference.h, narx_inference.c into esp32-firmware/sensing/src/")


if __name__ == "__main__":
    main()
