/**
 * narx_inference.c
 * Auto-generated by narx_export.py — DO NOT EDIT.
 *
 * Pure C NARX SOC inference for ESP32 / Arduino / ESP-IDF.
 * Dependencies: <math.h> only.
 *
 * Compile check (host):
 *   gcc -Wall -Wextra -std=c99 -lm narx_inference.c -o /dev/null
 */

#include "narx_inference.h"
#include "narx_weights.h"
#include <math.h>

/* ------------------------------------------------------------------ */
/*  Internal state                                                       */
/* ------------------------------------------------------------------ */

/* Circular buffers for sensor sliding window */
static float _v_buf[NARX_WINDOW_N];
static float _i_buf[NARX_WINDOW_N];
static float _t_buf[NARX_WINDOW_N];

/* SOC feedback buffer (stores last M normalized predictions) */
static float _soc_buf[NARX_FEEDBACK_M];

/* Write index into the circular buffers */
static int _buf_idx;

/* ------------------------------------------------------------------ */
/*  Helpers                                                              */
/* ------------------------------------------------------------------ */

static float _normalize(float val, float mn, float mx)
{
    float range = mx - mn;
    if (range < 1e-8f) range = 1e-8f;
    return (val - mn) / range;
}

static float _relu(float x)
{
    return x > 0.0f ? x : 0.0f;
}

static float _clampf(float x, float lo, float hi)
{
    if (x < lo) return lo;
    if (x > hi) return hi;
    return x;
}

/* ------------------------------------------------------------------ */
/*  Public API                                                           */
/* ------------------------------------------------------------------ */

void narx_init(void)
{
    int i;
    for (i = 0; i < NARX_WINDOW_N; i++) {
        _v_buf[i] = 0.0f;
        _i_buf[i] = 0.0f;
        _t_buf[i] = 0.0f;
    }
    /* Initialize SOC feedback at 0.5 (= 50% normalized) */
    for (i = 0; i < NARX_FEEDBACK_M; i++) {
        _soc_buf[i] = 0.5f;
    }
    _buf_idx = 0;
}

void narx_reset(float soc_percent)
{
    int i;
    float soc_norm;
    float range = NORM_SOC_MAX - NORM_SOC_MIN;
    if (range < 1e-8f) range = 1e-8f;
    soc_norm = _clampf((soc_percent - NORM_SOC_MIN) / range, 0.0f, 1.0f);
    for (i = 0; i < NARX_FEEDBACK_M; i++) {
        _soc_buf[i] = soc_norm;
    }
}

float narx_predict(float voltage_V, float current_A, float temperature_C)
{
    int i, j;
    int oldest;
    float input[NARX_INPUT_SIZE];
    float h1[NARX_HIDDEN1_SIZE];
    float h2[NARX_HIDDEN2_SIZE];
    float out;
    float soc_norm;

    /* ---- 1. Normalize inputs ---- */
    float v_n = _normalize(voltage_V,     NORM_V_MIN, NORM_V_MAX);
    float i_n = _normalize(current_A,     NORM_I_MIN, NORM_I_MAX);
    float t_n = _normalize(temperature_C, NORM_T_MIN, NORM_T_MAX);

    /* ---- 2. Write into circular buffers ---- */
    int slot = _buf_idx % NARX_WINDOW_N;
    _v_buf[slot] = v_n;
    _i_buf[slot] = i_n;
    _t_buf[slot] = t_n;
    _buf_idx++;

    /* ---- 3. Build flat input vector [v_win | i_win | t_win | soc_fb] ---- */
    /* oldest sample sits at (_buf_idx) % NARX_WINDOW_N */
    oldest = _buf_idx % NARX_WINDOW_N;
    for (j = 0; j < NARX_WINDOW_N; j++) {
        int idx = (oldest + j) % NARX_WINDOW_N;
        input[j]                      = _v_buf[idx];
        input[j + NARX_WINDOW_N]      = _i_buf[idx];
        input[j + 2 * NARX_WINDOW_N]  = _t_buf[idx];
    }
    for (j = 0; j < NARX_FEEDBACK_M; j++) {
        input[3 * NARX_WINDOW_N + j] = _soc_buf[j];
    }

    /* ---- 4. Forward pass: Dense1 (ReLU) ---- */
    for (i = 0; i < NARX_HIDDEN1_SIZE; i++) {
        h1[i] = b1[i];
        for (j = 0; j < NARX_INPUT_SIZE; j++) {
            h1[i] += input[j] * W1[j][i];
        }
        h1[i] = _relu(h1[i]);
    }

    /* ---- 5. Forward pass: Dense2 (ReLU) ---- */
    for (i = 0; i < NARX_HIDDEN2_SIZE; i++) {
        h2[i] = b2[i];
        for (j = 0; j < NARX_HIDDEN1_SIZE; j++) {
            h2[i] += h1[j] * W2[j][i];
        }
        h2[i] = _relu(h2[i]);
    }

    /* ---- 6. Forward pass: Dense3 (linear output) ---- */
    out = b3[0];
    for (j = 0; j < NARX_HIDDEN2_SIZE; j++) {
        out += h2[j] * W3[j][0];
    }

    /* ---- 7. Clamp to [0, 1] normalized range ---- */
    soc_norm = _clampf(out, 0.0f, 1.0f);

    /* ---- 8. Shift SOC feedback buffer and append new prediction ---- */
    for (j = 0; j < NARX_FEEDBACK_M - 1; j++) {
        _soc_buf[j] = _soc_buf[j + 1];
    }
    _soc_buf[NARX_FEEDBACK_M - 1] = soc_norm;

    /* ---- 9. Denormalize and return SOC percentage ---- */
    return soc_norm * (NORM_SOC_MAX - NORM_SOC_MIN) + NORM_SOC_MIN;
}
