/**
 * narx_inference.h
 * Auto-generated by narx_export.py — DO NOT EDIT.
 *
 * Public API for NARX SOC estimation on ESP32.
 *
 * Usage:
 *   #include "narx_inference.h"
 *
 *   // Call once in setup()
 *   narx_init();
 *
 *   // When the RPi sends a corrected SOC from the cloud LSTM, reset the buffer:
 *   narx_reset(cloud_soc_percent);
 *
 *   // Call every second in loop()
 *   float soc_percent = narx_predict(voltage_V, current_A, temperature_C);
 *
 * Input:
 *   voltage_V     — pack voltage in Volts (raw, unnormalized)
 *   current_A     — pack current in Amperes (negative = discharge). Pass 0.0f
 *                   if current is unavailable on the sensing ESP32.
 *   temperature_C — module temperature in °C (raw, unnormalized)
 *
 * Output:
 *   SOC in percent [0.0, 100.0]
 *
 * Architecture notes:
 *   The NARX model uses teacher-forced training and is most accurate immediately
 *   after narx_reset() is called with a cloud LSTM correction. The cloud LSTM
 *   (running on the RPi/Docker) is the authoritative SOC source; the NARX
 *   provides fast local tracking between cloud updates.
 */
#pragma once

#ifdef __cplusplus
extern "C" {
#endif

/**
 * Reset internal sliding-window and SOC feedback buffers.
 * Must be called once before the first narx_predict() call.
 */
void narx_init(void);

/**
 * Reset the SOC feedback buffer to a known value.
 * Call this whenever the cloud LSTM provides a corrected SOC estimate.
 *
 * soc_percent — known SOC in percent [0.0, 100.0]
 */
void narx_reset(float soc_percent);

/**
 * Run one step of NARX SOC estimation.
 * Returns predicted SOC in percent [0.0, 100.0].
 */
float narx_predict(float voltage_V, float current_A, float temperature_C);

#ifdef __cplusplus
}
#endif
